version: '3'
services: 
  tomcat:
    image: tomcat:latest
    links:
    - wordpress_db:mysql
    ports:
    - "7070:8080"
  wordpress_db:
    image: mariadb
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: prasant
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
    - wordpress_db:mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: prasant
    ports:
    - "9090:80"


